### ISSUE TITLE
ArrayIndexOutOfBoundsException when changing pitch while playing

### ISSUE THREAD

**Issue by ufoq** [waywardgeek/sonic#24]
I get it randomly while stress-testing (every few hundred ms I change pitch between 1.0 and 2.0 while playing) -> 
```   
java.lang.ArrayIndexOutOfBoundsException: length=6916; index=6916  at com.github.waywardgeek.sonic.Sonic.interpolate(Sonic.java:828) at com.github.waywardgeek.sonic.Sonic.adjustRate(Sonic.java:867) at com.github.waywardgeek.sonic.Sonic.processStreamInput(Sonic.java:978) at com.github.waywardgeek.sonic.Sonic.writeBytesToStream(Sonic.java:1018)
```
Exception is thrown here: https://github.com/waywardgeek/sonic/blob/71c51195de71627d7443d05378c680ba756545e8/Sonic.java#L829

I see that it is possible because buffer lengths boundaries for loops ignore SINC points here -> https://github.com/waywardgeek/sonic/blob/71c51195de71627d7443d05378c680ba756545e8/Sonic.java#L865

If I change:
```java
for (position = 0; position < numPitchSamples - 1; position++) {
```
to
```java
for (position = 0; position < numPitchSamples - 1 - SINC_FILTER_POINTS; position++) {
```
it works, but IDK how valid it is as I'm not an expert in audio maths.

**Comment by waywardgeek** [comment]
Thanks for catching this!  Your fix is correct.  I apparently fixed this in the C code, but not the Java.  I've updated Sonic.java to include the fix in a way that matches the C code a bit more closely.

**Comment by PaulWoitaschek** [comment]
Can you write a test that covers both implementations?
