### ISSUE TITLE
Removing Integer allocations from the Sonic Java port 

### ISSUE THREAD

**Issue by jedhoffmann** [waywardgeek/sonic#4]
Hi. I'm using Sonic in an Android application and it works great, much thanks for the library and for the Java port. I made a couple of small tweaks to avoid allocating Integers on what is a hot code path for me, and I'm wondering if you're interested in a pull request with my changes? Thanks.

**Comment by waywardgeek** [comment]
Sure, if you submit the pull request, I'll add it.  Thanks for tuning it.  By the way, sonic is now integrated directly into the AudioTrack, though unfortunately it is only in Android M forward:

http://developer.android.com/reference/android/media/AudioTrack.html#setPlaybackParams(android.media.PlaybackParams)

**Comment by jedhoffmann** [comment]
I was aware of the new AudioTrack capability but I didn't know it was using Sonic. That's great that Sonic has made it into the Android source. I submitted a pull request. I don't think there should be any side effects of the change, I have been running that code for the last couple of days without problems.
