### ISSUE TITLE
picola link is dead

### ISSUE THREAD

**Issue by ensonic** [waywardgeek/sonic#7]
In doc/index.md this url is referenced: http://keizai.yokkaichi-u.ac.jp/~ikeda/research/picola.html

The last cached version I found is this:
https://web.archive.org/web/20120731100136/http://keizai.yokkaichi-u.ac.jp/~ikeda/research/picola.html

Slighly off topic, the sonic.c source mentions 'AMDF', could you spell this out once (e.g. in the doc/index.md) - just found out after searching more that it is "Average Magnitude Difference Function".

Thanks!

**Comment by waywardgeek** [comment]
Done.
